server:
  port: 8080
  servlet:
    context-path: ${context_path:/}
spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  application:
    name: food-server
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://${db_host:10.0.4.16}:${db_port:3306}/${db_name:face}?useunicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: ${db_username:face}
    password: ${db_password:faceAa@123456}
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  codec:
    max-in-memory-size: 10MB
logging:
  level:
    com.coding.mapper: debug
    org.hibernate.engine.QueryParameters: debug
    org.hibernate.engine.query.HQLQueryPlan: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    cn.com.lc.dao: debug
guanweiming:
  s3:
    enabled: true
    access-key: ${s3_access_key:admin}
    secret-key: ${s3_secret_key:12345678Aa}
    url: ${s3_url:http://10.0.4.16:9000}
    bucket: ${s3_bucket:public}
    access-url: ${s3_url:http://1.117.170.117:9000}
  cors:
    enabled: true
mapper:
  mappers:
    - tk.mybatis.mapper.common.Mapper
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true
    use-column-label: true
  mapper-locations: classpath*:mapper/*.xml
